version: "3.0"
services:
 
  api:
    image: node
    container_name: "sc-johnson_api_qa"
    restart: always
    volumes:
      - ./api:/opt/sc-johnson-qa
    working_dir: "/opt/sc-johnson-qa"
    command: ["bash", "run.sh"]
    networks:
      - net_qa
  client:
    image: node
    container_name: "sc-johnson_client_qa"
    restart: always
    depends_on:
      - api
    volumes:
      - ./client:/opt/sc-johnson-qa
    working_dir: "/opt/sc-johnson-qa"
    environment:
      MODE: dev
      HOST: 0.0.0.0
      PORT: 3001
    command: ["bash", "run.sh"]
    networks:
      - net_qa
  proxy:
    image: nginx
    container_name: "sc-johnson_proxy_dev_qa"
    volumes:
      - ./proxy:/opt/sc-johnson-qa
    working_dir: "/opt/sc-johnson-qa"
    ports:
      - "8080:80"
    volumes:
      - ./proxy:/etc/nginx/conf.d
    depends_on:
      - api
      - client
    networks:
      - net_qa
networks:
  net_qa:
    driver: bridge
